FROM node:lts-alpine3.23 AS builder
WORKDIR /app
# Install deps and build
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM nginx:1.28.1-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
